import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/user_provider.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Grow Expense',
      
      // Tabs & Navigation
      'tab_home': 'Home',
      'tab_business': 'Business',
      'tab_invoices': 'Invoices',
      'tab_khata': 'Khata',
      'tab_analytics': 'Analytics',
      'tab_budgets': 'Budgets',
      'tab_payments': 'Payments',
      'nav_dashboard': 'Dashboard',
      'nav_settings': 'Settings',

      // Speed Dial Actions
      'speed_new_sale': 'New Sale / GST Bill',
      'speed_new_sale_sub': 'Cash / Udhar + Bill PDF',
      'speed_business_expense': 'Business Expense',
      'speed_business_expense_sub': 'Stock, Rent, Bills, Salary',
      'speed_voice_entry': 'AI Voice Entry',
      'speed_voice_entry_sub': 'Speak sale or expense',
      'speed_ocr_scan': 'Smart OCR Scan',
      'speed_ocr_scan_sub': 'Scan vendor bills & receipts',

      // General & Common Actions
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'change': 'Change',
      'search': 'Search',
      'filter': 'Filter',
      'add': 'Add',
      'close': 'Close',
      'done': 'Done',
      'total': 'Total',
      'active': 'Active',
      'configured': 'Configured',
      'personal': 'Personal',
      'business': 'Business',

      // Metrics & Finances
      'sales': 'Sales',
      'expenses': 'Expenses',
      'net_profit': 'Net Profit & Margin',
      'margin': 'Margin',
      'to_receive': 'To Receive',
      'to_pay': 'To Pay',
      'you_will_get': 'You Will Get',
      'you_will_give': 'You Will Give',
      'customer_udhar': 'Customer Udhar',
      'vendor_payable': 'Vendor Payable',
      'total_outstanding': 'Total Outstanding',
      'recent_transactions': 'Recent Transactions',
      'quick_actions': 'Quick Actions',
      'new_sale': 'New Sale',
      'business_expense': 'Business Expense',
      'cash_flow': 'Cash Flow',
      'this_month': 'This Month',
      'today': 'Today',
      'this_week': 'This Week',
      'last_month': 'Last Month',
      'all_time': 'All Time',

      // Settings Headers & Items
      'settings_title': 'Settings',
      'app_working_mode': 'APP WORKING MODE',
      'active_profile': 'ACTIVE PROFILE',
      'business_mode_badge': 'BUSINESS MODE',
      'personal_mode_badge': 'PERSONAL MODE',
      'mode_biz_caption': 'Sales billing, GST invoices, customer Udhar Khata & Business Net Profit enabled.',
      'mode_personal_caption': 'Personal budgeting, daily expenses, subscriptions & trip tags enabled.',
      'biz_settings_title': 'Business Settings',
      'biz_settings_sub': 'Shop profile, GSTIN, UPI details & Product Catalog',
      'ai_config_title': 'AI Configuration',
      'ai_config_sub': 'API keys for Voice AI & Smart Scan',
      'ai_configured': 'CONFIGURED',
      'ai_setup_required': 'SETUP REQUIRED',
      'backup_sync_title': 'Backup & Cloud Sync',
      'backup_sync_sub': 'Auto-backup enabled • Tap to manage & restore',
      'syncing': 'SYNCING',
      'appearance_theme': 'APPEARANCE & THEME',
      'app_theme': 'App Theme',
      'theme_system': 'Device Default (System)',
      'theme_dark': 'Dark Mode',
      'theme_light': 'Light Mode',
      'app_language': 'App Language',
      'select_language': 'Select App Language',
      'max_refresh_rate': 'Max Refresh Rate (120Hz / 90Hz)',
      'max_refresh_rate_sub': 'Unlock ultra-smooth frame rate (Default ON)',
      'security_preferences': 'SECURITY & PREFERENCES',
      'biometric_lock': 'Biometric / Device Lock',
      'biometric_lock_sub': 'Lock app access with fingerprint / screen lock',
      'spending_forecast': 'Spending Forecast & Runway',
      'spending_forecast_sub': 'Show burn rate & budget forecast inside Budgets screen',
      'financial_records': 'FINANCIAL RECORDS',
      'saved_payment_accounts': 'Saved Payment Accounts',
      'saved_payment_accounts_sub': 'Manage linked bank and UPI accounts',
      'updates_system': 'UPDATES & SYSTEM',
      'app_updates': 'App Updates',
      'data_backup': 'DATA & BACKUP',
      'cloud_sync': 'Backup & Cloud Sync',
      'ai_extensions': 'AI & SMART EXTENSIONS',
      'ai_config': 'AI & Smart Recognition',
      'business_settings': 'BUSINESS SETTINGS',
      'notifications_settings': 'Notification Settings',
      'notifications_settings_sub': 'Master on/off, alert language & feature reminders',
      'notifications': 'Notification Alerts',
      'help_support': 'HELP & SUPPORT',
      'help_report': 'Help & Problem Report',
      'help_report_sub': 'Encountered an error or bug? Contact developer directly',
      'report_issue': 'Report an Issue / Feedback',
      'about_app': 'About App & Developer',
      'about_app_sub': 'Developer social handles, project repo & support',
      'account_session': 'ACCOUNT & SESSION',
      'logout': 'Log Out',
      'delete_account': 'Delete Account',

      // Languages
      'lang_en': 'English (Default)',
      'lang_hi': 'हिंदी (Hindi)',
      'lang_bn': 'বাংলা (Bengali)',

      // Common Dialogs & Actions
      'signout_title': 'Sign Out',
      'signout_confirm': 'Are you sure you want to sign out from this device?',
      'delete_acc_title': 'Delete Account?',
      'delete_acc_warning': 'Warning: This action is permanent and irreversible.',
      'delete_acc_desc': 'Your account and all associated data (transactions, statement history, budgets, UPI settings) will be permanently deleted from the cloud database and local storage.',
      'permanently_delete': 'Permanently Delete',
      'edit_profile_title': 'Edit Profile Details',
      'display_name': 'Display Name',
      'enter_name_hint': 'Enter your name',
      'profile_image_url': 'Profile Image URL',
      'profile_image_hint': 'Paste image link (optional)',
      'save_changes': 'Save Changes',
      'choose_app_theme': 'Choose App Theme',
      'choose_theme_sub': 'Select light, dark, or system default display mode',
      'choose_app_language': 'Choose App Language',
      'choose_lang_sub': 'Select your preferred display & AI chat response language',
      'screen_refresh_rate': 'Screen Refresh Rate',
      'refresh_rate_sub': 'Optimize for smoothest scrolling & 120Hz display responsiveness',
      'standard_60hz': 'Standard (60Hz)',
      'standard_60hz_desc': 'Standard refresh rate for power saving',
      'smooth_90hz': 'Smooth (90Hz)',
      'smooth_90hz_desc': 'Balanced smoothness & battery consumption',
      'ultra_120hz': 'Ultra Smooth (120Hz)',
      'ultra_120hz_desc': 'Maximum fluid animations & peak responsiveness',

      // Business Settings Screen
      'biz_profile_title': 'Business & Shop Profile',
      'biz_profile_sub': 'Configure shop details for invoices, GST billing, UPI QR & fast product catalog.',
      'biz_shop_name': 'Shop / Business Name',
      'biz_owner_name': 'Owner / Contact Name',
      'biz_phone': 'Phone / WhatsApp Number',
      'biz_address': 'Shop Address / Location',
      'biz_gstin': 'GSTIN (Tax Number)',
      'biz_upi_id': 'UPI Payment ID (VPA)',
      'biz_upi_name': 'Beneficiary / Account Name',
      'biz_catalog_title': 'Product / Item Catalog',
      'biz_catalog_sub': 'Manage items, prices, barcodes & stock deduction',
      'biz_open_catalog': 'Open Product Catalog',
      'biz_save_details': 'Save Business Details',

      // Notification Settings Screen
      'notif_settings_title': 'Notification Settings',
      'notif_master': 'Master Notifications',
      'notif_master_sub': 'Enable or disable all app notifications',
      'notif_lang': 'Notification Language',
      'notif_lang_sub': 'Choose language for notifications & alerts',
      'notif_daily_reminder': 'Daily Evening Expense Reminder',
      'notif_daily_reminder_sub': 'Get reminded at 9:00 PM to record today’s expenses',
      'notif_bills_sub': 'Bill & Subscription Reminders',
      'notif_bills_sub_desc': 'Receive advance alerts 3 days & 1 day before due date',
      'notif_monthly_reset': 'Monthly Reset & PDF Reminder',
      'notif_monthly_reset_sub': 'Start of month alert to download last month statement PDF',
      'notif_low_stock': 'Low Stock & Inventory Alerts',
      'notif_low_stock_sub': 'Get alerts when catalog stock falls below minimum threshold',
      'notif_test_header': 'Test Notifications',
    },
    'hi': {
      'app_name': 'ग्रो एक्सपेंस',

      // Tabs & Navigation
      'tab_home': 'होम',
      'tab_business': 'दुकान/व्यापार',
      'tab_invoices': 'इनवॉइस',
      'tab_khata': 'खाता बुक',
      'tab_analytics': 'एनालिटिक्स',
      'tab_budgets': 'बजट',
      'tab_payments': 'पेमेंट्स',
      'nav_dashboard': 'डैशबोर्ड',
      'nav_settings': 'सेटिंग्स',

      // Speed Dial Actions
      'speed_new_sale': 'नई बिक्री / बिल',
      'speed_new_sale_sub': 'नकद / उधार + बिल PDF',
      'speed_business_expense': 'दुकान का खर्चा',
      'speed_business_expense_sub': 'स्टॉक, किराया, बिजली, सैलरी',
      'speed_voice_entry': 'AI वॉइस एंट्री',
      'speed_voice_entry_sub': 'बोलकर हिसाब जोड़ें',
      'speed_ocr_scan': 'स्मार्ट बिल स्कैन',
      'speed_ocr_scan_sub': 'रसीद व बिल स्कैन करें',

      // General & Common Actions
      'save': 'सुरक्षित करें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'बदलें',
      'change': 'बदलें',
      'search': 'खोजें',
      'filter': 'फ़िल्टर',
      'add': 'जोड़ें',
      'close': 'बंद करें',
      'done': 'संपन्न',
      'total': 'कुल',
      'active': 'सक्रिय',
      'configured': 'सेट है',
      'personal': 'व्यक्तिगत (Personal)',
      'business': 'व्यापार (Business)',

      // Metrics & Finances
      'sales': 'कुल बिक्री',
      'expenses': 'कुल खर्चे',
      'net_profit': 'शुद्ध लाभ एवं मार्जिन',
      'margin': 'मार्जिन',
      'to_receive': 'पाना है',
      'to_pay': 'देना है',
      'you_will_get': 'आपको मिलेगा',
      'you_will_give': 'आपको देना है',
      'customer_udhar': 'ग्राहक उधार',
      'vendor_payable': 'सप्लायर बकाया',
      'total_outstanding': 'कुल बकाया',
      'recent_transactions': 'हालिया लेनदेन',
      'quick_actions': 'त्वरित कार्य',
      'new_sale': 'नई बिक्री',
      'business_expense': 'दुकान का खर्चा',
      'cash_flow': 'कैश फ्लो',
      'this_month': 'इस महीने',
      'today': 'आज',
      'this_week': 'इस हफ्ते',
      'last_month': 'पिछले महीने',
      'all_time': 'शुरू से अब तक',

      // Settings Headers & Items
      'settings_title': 'सेटिंग्स',
      'app_working_mode': 'ऐप वर्किंग मोड',
      'active_profile': 'सक्रिय प्रोफ़ाइल',
      'business_mode_badge': 'व्यापार मोड (BUSINESS)',
      'personal_mode_badge': 'व्यक्तिगत मोड (PERSONAL)',
      'mode_biz_caption': 'बिक्री बिलिंग, GST इनवॉइस, ग्राहक उधार खाता और शुद्ध लाभ सक्षम है।',
      'mode_personal_caption': 'व्यक्तिगत बजट, दैनिक खर्चे, सब्सक्रिप्शन और ट्रिप टैग्स सक्षम हैं।',
      'biz_settings_title': 'व्यापार सेटिंग्स',
      'biz_settings_sub': 'दुकान प्रोफ़ाइल, GSTIN, UPI विवरण और सामान कैटलॉग',
      'ai_config_title': 'AI सेटिंग्स',
      'ai_config_sub': 'AI वॉइस और स्मार्ट बिल स्कैन के लिए API कुंजी',
      'ai_configured': 'सेट है',
      'ai_setup_required': 'सेटअप करें',
      'backup_sync_title': 'बैकअप एवं क्लाउड सिंक',
      'backup_sync_sub': 'ऑटो-बैकअप सक्रिय है • डेटा प्रबंधित और रिस्टोर करें',
      'syncing': 'सिंक हो रहा है',
      'appearance_theme': 'दिखावट एवं थीम',
      'app_theme': 'ऐप थीम',
      'theme_system': 'डिवाइस डिफ़ॉल्ट (सिस्टम)',
      'theme_dark': 'डार्क मोड',
      'theme_light': 'लाइट मोड',
      'app_language': 'ऐप की भाषा (App Language)',
      'select_language': 'ऐप की भाषा चुनें',
      'max_refresh_rate': 'सुपर स्मूथ फ्रेम रेट (120Hz / 90Hz)',
      'max_refresh_rate_sub': 'अल्ट्रा स्मूथ फ्रेम रेट अनलॉक करें',
      'security_preferences': 'सुरक्षा एवं प्राथमिकताएं',
      'biometric_lock': 'फिंगरप्रिंट / स्क्रीन लॉक',
      'biometric_lock_sub': 'फिंगरप्रिंट या स्क्रीन लॉक से ऐप सुरक्षित करें',
      'spending_forecast': 'खर्च पूर्वानुमान एवं रनवे',
      'spending_forecast_sub': 'बजट स्क्रीन में खर्च की गति और पूर्वानुमान देखें',
      'financial_records': 'वित्तीय रिकॉर्ड्स',
      'saved_payment_accounts': 'सेव किए गए खाते व UPI',
      'saved_payment_accounts_sub': 'बैंक खाते और UPI IDs प्रबंधित करें',
      'updates_system': 'अपडेट्स एवं सिस्टम',
      'app_updates': 'ऐप अपडेट्स',
      'data_backup': 'डेटा एवं बैकअप',
      'cloud_sync': 'बैकअप एवं क्लाउड सिंक',
      'ai_extensions': 'AI एवं स्मार्ट सुविधाएं',
      'ai_config': 'AI सलाहकार एवं मान्यता',
      'business_settings': 'व्यापार सेटिंग्स (GST, दुकान)',
      'notifications_settings': 'नोटिफ़िकेशन सेटिंग्स',
      'notifications_settings_sub': 'अलर्ट्स, भाषा और रिमाइंडर प्रबंधित करें',
      'notifications': 'अलर्ट्स व नोटिफ़िकेशन',
      'help_support': 'सहायता एवं फ़ीडबैक',
      'help_report': 'सहायता एवं समस्या बताएं',
      'help_report_sub': 'कोई समस्या या बग मिला? डेवलपर से सीधा संपर्क करें',
      'report_issue': 'समस्या बताएं / फ़ीडबैक भेजें',
      'about_app': 'ऐप एवं डेवलपर के बारे में',
      'about_app_sub': 'डेवलपर संपर्क, प्रोजेक्ट कोड एवं सहायता',
      'account_session': 'अकाउंट एवं सत्र',
      'logout': 'लॉग आउट',
      'delete_account': 'अकाउंट हटाएं',

      // Languages
      'lang_en': 'English (अंग्रेज़ी)',
      'lang_hi': 'हिंदी (Hindi)',
      'lang_bn': 'বাংলা (बंगाली)',

      // Common Dialogs & Actions
      'signout_title': 'लॉग आउट',
      'signout_confirm': 'क्या आप इस डिवाइस से लॉग आउट करना चाहते हैं?',
      'delete_acc_title': 'अकाउंट हटाएं?',
      'delete_acc_warning': 'चेतावनी: यह क्रिया स्थायी है और वापस नहीं ली जा सकती।',
      'delete_acc_desc': 'आपका खाता और उससे जुड़ा सारा डेटा (लेनदेन, बिल, बजट, UPI सेटिंग्स) हमेशा के लिए मिटा दिया जाएगा।',
      'permanently_delete': 'हमेशा के लिए हटाएं',
      'edit_profile_title': 'प्रोफ़ाइल विवरण बदलें',
      'display_name': 'नाम (Display Name)',
      'enter_name_hint': 'अपना नाम दर्ज करें',
      'profile_image_url': 'प्रोफ़ाइल फोटो URL',
      'profile_image_hint': 'फोटो का लिंक पेस्ट करें (वैकल्पिक)',
      'save_changes': 'बदलाव सुरक्षित करें',
      'choose_app_theme': 'ऐप थीम चुनें',
      'choose_theme_sub': 'लाइट, डार्क या सिस्टम डिफ़ॉल्ट मोड चुनें',
      'choose_app_language': 'ऐप की भाषा चुनें',
      'choose_lang_sub': 'अपनी पसंदीदा ऐप एवं AI प्रतिक्रिया भाषा चुनें',
      'screen_refresh_rate': 'स्क्रीन रिफ्रेश रेट',
      'refresh_rate_sub': 'सुपर स्मूथ स्क्रॉलिंग और 120Hz डिस्प्ले के लिए',
      'standard_60hz': 'मानक (60Hz)',
      'standard_60hz_desc': 'बैटरी बचाने के लिए सामान्य रिफ्रेश रेट',
      'smooth_90hz': 'स्मूथ (90Hz)',
      'smooth_90hz_desc': 'संतुलित स्मूथनेस एवं बैटरी जीवन',
      'ultra_120hz': 'अल्ट्रा स्मूथ (120Hz)',
      'ultra_120hz_desc': 'बेहतरीन स्मूथ स्क्रॉलिंग और गति',

      // Business Settings Screen
      'biz_profile_title': 'दुकान व व्यापार प्रोफ़ाइल',
      'biz_profile_sub': 'इनवॉइस, GST बिलिंग, UPI QR और सामान कैटलॉग के लिए दुकान का विवरण भरें।',
      'biz_shop_name': 'दुकान / व्यापार का नाम',
      'biz_owner_name': 'मालिक / संपर्क व्यक्ति का नाम',
      'biz_phone': 'फ़ोन / व्हाट्सएप नंबर',
      'biz_address': 'दुकान का पता / स्थान',
      'biz_gstin': 'GSTIN (टैक्स नंबर)',
      'biz_upi_id': 'UPI पेमेंट ID (VPA)',
      'biz_upi_name': 'खाताधारक / लाभार्थी का नाम',
      'biz_catalog_title': 'सामान / प्रॉडक्ट कैटलॉग',
      'biz_catalog_sub': 'सामान, मूल्य, बारकोड और स्टॉक ऑटो-कटौती प्रबंधित करें',
      'biz_open_catalog': 'प्रॉडक्ट कैटलॉग खोलें',
      'biz_save_details': 'व्यापार विवरण सुरक्षित करें',

      // Notification Settings Screen
      'notif_settings_title': 'नोटिफ़िकेशन सेटिंग्स',
      'notif_master': 'मास्टर नोटिफ़िकेशन',
      'notif_master_sub': 'ऐप के सभी नोटिफ़िकेशन चालू या बंद करें',
      'notif_lang': 'नोटिफ़िकेशन की भाषा',
      'notif_lang_sub': 'अलर्ट्स व नोटिफ़िकेशन के लिए भाषा चुनें',
      'notif_daily_reminder': 'दैनिक शाम का खर्च रिमाइंडर',
      'notif_daily_reminder_sub': 'हर शाम 9:00 बजे आज का खर्च लिखने का रिमाइंडर प्राप्त करें',
      'notif_bills_sub': 'बिल एवं सब्सक्रिप्शन रिमाइंडर',
      'notif_bills_sub_desc': 'अंतिम तिथि से 3 दिन और 1 दिन पहले समय पर अलर्ट प्राप्त करें',
      'notif_monthly_reset': 'मासिक सारांश एवं PDF रिमाइंडर',
      'notif_monthly_reset_sub': 'महीने की शुरुआत में पिछले महीने का PDF डाउनलोड करने का अलर्ट',
      'notif_low_stock': 'कम स्टॉक एवं इन्वेंटरी अलर्ट',
      'notif_low_stock_sub': 'सामान का स्टॉक न्यूनतम सीमा से कम होने पर तुरंत अलर्ट पाएं',
      'notif_test_header': 'नोटिफ़िकेशन टेस्ट करें',
    },
    'bn': {
      'app_name': 'গ্রো এক্সপেন্স',

      // Tabs & Navigation
      'tab_home': 'হোম',
      'tab_business': 'ব্যবসা/দোকান',
      'tab_invoices': 'ইনভয়েস',
      'tab_khata': 'খাতা বুক',
      'tab_analytics': 'অ্যানালিটিক্স',
      'tab_budgets': 'বাজেট',
      'tab_payments': 'পেমেন্টস',
      'nav_dashboard': 'ড্যাশবোর্ড',
      'nav_settings': 'সেটিংস',

      // Speed Dial Actions
      'speed_new_sale': 'নতুন বিক্রি / বিল',
      'speed_new_sale_sub': 'নগদ / বাকি + বিল PDF',
      'speed_business_expense': 'দোকানের খরচ',
      'speed_business_expense_sub': 'স্টক, ভাড়া, বিল, বেতন',
      'speed_voice_entry': 'AI ভয়েস এন্ট্রি',
      'speed_voice_entry_sub': 'মুখে বলে হিসাব যোগ করুন',
      'speed_ocr_scan': 'স্মার্ট বিল স্ক্যান',
      'speed_ocr_scan_sub': 'রসিদ ও বিল স্ক্যান করুন',

      // General & Common Actions
      'save': 'সংরক্ষণ করুন',
      'cancel': 'বাতিল',
      'delete': 'মুছুন',
      'edit': 'সম্পাদনা',
      'change': 'পরিবর্তন',
      'search': 'অনুসন্ধান',
      'filter': 'ফিল্টার',
      'add': 'যুক্ত করুন',
      'close': 'বন্ধ করুন',
      'done': 'সম্পন্ন',
      'total': 'মোট',
      'active': 'সক্রিয়',
      'configured': 'সেট আছে',
      'personal': 'ব্যক্তিগত (Personal)',
      'business': 'ব্যবসা (Business)',

      // Metrics & Finances
      'sales': 'মোট বিক্রি',
      'expenses': 'মোট খরচ',
      'net_profit': 'নিট লাভ ও মার্জিন',
      'margin': 'মার্জিন',
      'to_receive': 'পাওনা (To Receive)',
      'to_pay': 'দেনা (To Pay)',
      'you_will_get': 'আপনি পাবেন',
      'you_will_give': 'আপনি দেবেন',
      'customer_udhar': 'কাস্টমার বাকি',
      'vendor_payable': 'মহাজন বাকি',
      'total_outstanding': 'মোট বাকি',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'quick_actions': 'দ্রুত অ্যাকশন',
      'new_sale': 'নতুন বিক্রি',
      'business_expense': 'দোকানের খরচ',
      'cash_flow': 'ক্যাশ ফ্লো',
      'this_month': 'এই মাস',
      'today': 'আজ',
      'this_week': 'এই সপ্তাহ',
      'last_month': 'গত মাস',
      'all_time': 'সর্বমোট',

      // Settings Headers & Items
      'settings_title': 'সেটিংস',
      'app_working_mode': 'অ্যাপের কাজের মোড',
      'active_profile': 'সক্রিয় প্রোফাইল',
      'business_mode_badge': 'ব্যবসা মোড (BUSINESS)',
      'personal_mode_badge': 'ব্যক্তিগত মোড (PERSONAL)',
      'mode_biz_caption': 'বিক্রি বিলিং, GST চালান, কাস্টমার বাকি খাতা এবং নিট লাভ সক্রিয় আছে।',
      'mode_personal_caption': 'ব্যক্তিগত বাজেট, দৈনিক খরচ, সাবস্ক্রিপশন এবং ট্রিপ ট্যাগ সক্রিয় আছে।',
      'biz_settings_title': 'ব্যবসার সেটিংস',
      'biz_settings_sub': 'দোকানের প্রোফাইল, GSTIN, UPI বিবরণ ও পণ্যের ক্যাটালগ',
      'ai_config_title': 'AI সেটিংস',
      'ai_config_sub': 'AI ভয়েস ও স্মার্ট স্ক্যানের জন্য API চাবি',
      'ai_configured': 'সেট আছে',
      'ai_setup_required': 'সেটআপ প্রয়োজন',
      'backup_sync_title': 'ব্যাকআপ ও ক্লাউড সিঙ্ক',
      'backup_sync_sub': 'অটো-ব্যাকআপ সক্রিয় • ডাটা পরিচালনা ও পুনরুদ্ধার করুন',
      'syncing': 'সিঙ্ক হচ্ছে',
      'appearance_theme': 'রূপ ও থিম',
      'app_theme': 'অ্যাপ থিম',
      'theme_system': 'ডিভাইস ডিফল্ট (সিস্টেম)',
      'theme_dark': 'ডার্ক মোড',
      'theme_light': 'লাইট মোড',
      'app_language': 'অ্যাপের ভাষা (App Language)',
      'select_language': 'অ্যাপের ভাষা নির্বাচন করুন',
      'max_refresh_rate': 'আল্ট্রা স্মুথ ফ্রেম রেট (120Hz / 90Hz)',
      'max_refresh_rate_sub': 'সুপার স্মুথ ফ্রেম রেট আনলক করুন',
      'security_preferences': 'নিরাপত্তা ও পছন্দ',
      'biometric_lock': 'ফিঙ্গারপ্রিন্ট / স্ক্রিন লক',
      'biometric_lock_sub': 'ফিঙ্গারপ্রিন্ট বা স্ক্রিন লক দিয়ে অ্যাপ সুরক্ষিত রাখুন',
      'spending_forecast': 'খরচ পূর্বাভাস ও রানওয়ে',
      'spending_forecast_sub': 'বাজেট স্ক্রিনে ব্যয়ের গতি ও পূর্বাভাস দেখুন',
      'financial_records': 'আর্থিক রেকর্ডস',
      'saved_payment_accounts': 'সংরক্ষিত ব্যাংক ও UPI অ্যাকাউন্ট',
      'saved_payment_accounts_sub': 'সংযুক্ত ব্যাংক ও UPI অ্যাকাউন্ট পরিচালনা করুন',
      'updates_system': 'আপডেট ও সিস্টেম',
      'app_updates': 'অ্যাপ আপডেট',
      'data_backup': 'ডাটা ও ব্যাকআপ',
      'cloud_sync': 'ব্যাকআপ ও ক্লাউড সিঙ্ক',
      'ai_extensions': 'AI ও স্মার্ট ফিচার',
      'ai_config': 'AI সহকারী কনফিগারেশন',
      'business_settings': 'ব্যবসার সেটিংস (GST, দোকান)',
      'notifications_settings': 'বিজ্ঞপ্তি সেটিংস',
      'notifications_settings_sub': 'অ্যালার্ট, ভাষা ও রিমাইন্ডার পরিচালনা করুন',
      'notifications': 'বিজ্ঞপ্তি অ্যালার্ট',
      'help_support': 'সহায়তা ও প্রতিক্রিয়া',
      'help_report': 'সহায়তা ও সমস্যা জানান',
      'help_report_sub': 'কোনো সমস্যা হয়েছে? সরাসরি ডেভেলপারের সাথে যোগাযোগ করুন',
      'report_issue': 'সমস্যা জানান / প্রতিক্রিয়া দিন',
      'about_app': 'অ্যাপ ও ডেভেলপার সম্পর্কে',
      'about_app_sub': 'ডেভেলপার পরিচিতি, প্রজেক্ট লিঙ্ক ও সহায়তা',
      'account_session': 'অ্যাকাউন্ট ও সেশন',
      'logout': 'লগ আউট',
      'delete_account': 'অ্যাকাউন্ট মুছুন',

      // Languages
      'lang_en': 'English (ইংরেজি)',
      'lang_hi': 'हिंदी (হিন্দি)',
      'lang_bn': 'বাংলা (Bengali)',

      // Common Dialogs & Actions
      'signout_title': 'লগ আউট',
      'signout_confirm': 'আপনি কি এই ডিভাইস থেকে লগ আউট করতে নিশ্চিত?',
      'delete_acc_title': 'অ্যাকাউন্ট মুছবেন?',
      'delete_acc_warning': 'সতর্কতা: এই পদক্ষেপটি স্থায়ী এবং অপরিবর্তনীয়।',
      'delete_acc_desc': 'আপনার অ্যাকাউন্ট এবং সমস্ত সংশ্লিষ্ট ডাটা (লেনদেন, বিল, বাজেট, UPI সেটিংস) ক্লাউড ডাটাবেস ও ফোন থেকে স্থায়ীভাবে মুছে যাবে।',
      'permanently_delete': 'স্থায়ীভাবে মুছুন',
      'edit_profile_title': 'প্রোফাইল বিবরণ পরিবর্তন',
      'display_name': 'নাম (Display Name)',
      'enter_name_hint': 'আপনার নাম লিখুন',
      'profile_image_url': 'প্রোফাইল ছবির URL',
      'profile_image_hint': 'ছবির লিঙ্ক পেস্ট করুন (ঐচ্ছিক)',
      'save_changes': 'পরিবর্তন সংরক্ষণ করুন',
      'choose_app_theme': 'অ্যাপ থিম নির্বাচন করুন',
      'choose_theme_sub': 'লাইট, ডার্ক বা সিস্টেম ডিফল্ট মোড বেছে নিন',
      'choose_app_language': 'অ্যাপের ভাষা নির্বাচন করুন',
      'choose_lang_sub': 'আপনার পছন্দের ডিসপ্লে ও AI উত্তরের ভাষা বেছে নিন',
      'screen_refresh_rate': 'স্ক্রিন রিফ্রেশ রেট',
      'refresh_rate_sub': 'সুপার স্মুথ স্ক্রলিং এবং 120Hz ডিসপ্লে রেসপন্সিভনেস',
      'standard_60hz': 'স্ট্যান্ডার্ড (60Hz)',
      'standard_60hz_desc': 'ব্যাটারি সাশ্রয়ের জন্য স্বাভাবিক রিফ্রেশ রেট',
      'smooth_90hz': 'স্মুথ (90Hz)',
      'smooth_90hz_desc': 'ভারসাম্যপূর্ণ স্মুথনেস ও ব্যাটারি সাশ্রয়',
      'ultra_120hz': 'আল্ট্রা স্মুথ (120Hz)',
      'ultra_120hz_desc': 'সবচেয়ে দ্রুত এবং ফ্লুইড অ্যানিমেশন',

      // Business Settings Screen
      'biz_profile_title': 'দোকান ও ব্যবসার প্রোফাইল',
      'biz_profile_sub': 'ইনভয়েস, GST চালান, UPI QR ও পণ্য তালিকার জন্য দোকানের বিবরণ দিন।',
      'biz_shop_name': 'দোকান / ব্যবসার নাম',
      'biz_owner_name': 'মালিক / যোগাযোগের ব্যক্তির নাম',
      'biz_phone': 'ফোন / হোয়াটসঅ্যাপ নম্বর',
      'biz_address': 'দোকানের ঠিকানা / অবস্থান',
      'biz_gstin': 'GSTIN (ট্যাক্স নম্বর)',
      'biz_upi_id': 'UPI পেমেন্ট ID (VPA)',
      'biz_upi_name': 'অ্যাকাউন্টের নাম / সুবিধাভোগী',
      'biz_catalog_title': 'পণ্য / স্টক ক্যাটালগ',
      'biz_catalog_sub': 'পণ্য, দাম, বারকোড ও স্টক স্বয়ংক্রিয় কর্তন পরিচালনা করুন',
      'biz_open_catalog': 'পণ্য ক্যাটালগ খুলুন',
      'biz_save_details': 'ব্যবসার বিবরণ সংরক্ষণ করুন',

      // Notification Settings Screen
      'notif_settings_title': 'বিজ্ঞপ্তি সেটিংস',
      'notif_master': 'মাস্টার নোটিফিকেশন',
      'notif_master_sub': 'অ্যাপের সমস্ত বিজ্ঞপ্তি চালু বা বন্ধ করুন',
      'notif_lang': 'বিজ্ঞপ্তির ভাষা',
      'notif_lang_sub': 'অ্যালার্ট ও নোটিফিকেশনের ভাষা নির্বাচন করুন',
      'notif_daily_reminder': 'দৈনিক সান্ধ্যকালীন খরচ রিমাইন্ডার',
      'notif_daily_reminder_sub': 'প্রতিদিন রাত ৯:০০ টায় আজকের খরচ লেখার রিমাইন্ডার পান',
      'notif_bills_sub': 'বিল ও সাবস্ক্রিপশন রিমাইন্ডার',
      'notif_bills_sub_desc': 'নির্দিষ্ট তারিখের ৩ দিন ও ১ দিন আগে অ্যালার্ট পান',
      'notif_monthly_reset': 'মাসিক বিবরণী ও PDF রিমাইন্ডার',
      'notif_monthly_reset_sub': 'মাসের শুরুতে গত মাসের খরচের PDF ডাউনলোড অ্যালার্ট পান',
      'notif_low_stock': 'কম স্টক ও ইনভেন্টরি অ্যালার্ট',
      'notif_low_stock_sub': 'পণ্য স্টক কমলে সাথে সাথে সতর্কতা পান',
      'notif_test_header': 'বিজ্ঞপ্তি পরীক্ষা করুন',
    },
  };

  /// Get translation by key with context
  static String tr(BuildContext context, String key) {
    try {
      final lang = Provider.of<UserProvider>(context, listen: true).appLanguage;
      return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
    } catch (_) {
      return _localizedValues['en']?[key] ?? key;
    }
  }

  /// Get translation by key and explicit language code
  static String get(String key, [String lang = 'en']) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  /// Get human-readable language label with flag
  static String getLanguageLabel(String code) {
    switch (code) {
      case 'hi':
        return '🇮🇳 हिंदी (Hindi)';
      case 'bn':
        return '🇮🇳 বাংলা (Bengali)';
      case 'en':
      default:
        return '🇬🇧 English (Default)';
    }
  }
}
